#!/bin/bash
# Auto-generated by cproj --doctor
# Project: sigma.collections
# Date: 2026-02-15 08:32:36

set -e

TOOLS_BUILDS_DIR="/home/badkraft/repos/tools/projects/../builds"

echo "Applying fixes to sigma.collections..."
echo ""

# Fix: Replace BUILDING.md copy with symlink
if [ -f "BUILDING.md" ] && [ ! -L "BUILDING.md" ]; then
    echo "→ Symlinking BUILDING.md"
    mv BUILDING.md BUILDING.md.bak
    ln -s "$TOOLS_BUILDS_DIR/BUILDING.md" BUILDING.md
    echo "  Backup saved: BUILDING.md.bak"
fi

# Fix: Update VS Code launch.json version
if [ -f ".vscode/launch.json" ]; then
    echo "→ Fixing launch.json version"
    sed -i 's/"version": "0.2.1"/"version": "0.2.0"/' .vscode/launch.json
fi


echo ""
echo "✓ Fixes applied successfully"
